version: '3.8'
name: rinha-de-backend-lbaesso-dotnet
services:

  app1: &app
    container_name: app1
    build:
      context: ./app
      dockerfile: dockerfile
    depends_on:
      - postgres
    networks:
      - rinha-net
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=rinha
      - DB_MIN_POOL_SIZE=4
      - DB_MAX_POOL_SIZE=8
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"

  app2:
    <<: *app
    container_name: app2

  gateway:
    container_name: gateway
    image: nginx:latest
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "40MB"
    networks:
      - rinha-net

  # gateway:
  #   container_name: gateway
  #   image: haproxy:latest
  #   volumes:
  #     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  #   ports:
  #     - 9999:9999
  #   expose:
  #     - 9999
  #   networks:
  #     - rinha-net
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.30"
    #       memory: "80MB"

  # gateway:
  #   container_name: gateway
  #   image: envoyproxy/envoy:dev
  #   volumes:
  #     - ./envoy.yaml:/etc/envoy/envoy.yaml
  #   ports:
  #     - 9999:9999
  #   expose:
  #     - 9999
  #   networks:
  #     - rinha-net
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.30"
  #         memory: "40MB"

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    command: postgres -c 'max_connections=64' -c 'shared_buffers=240MB'
    networks:
      - rinha-net
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "310MB"

networks:
  rinha-net:
    driver: bridge
    name: rinha-net