FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
RUN apt-get update && apt-get install -y clang zlib1g-dev
COPY ["rinha-dot-net-aot.csproj", ""]
RUN dotnet restore "./rinha-dot-net-aot.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "rinha-dot-net-aot.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "rinha-dot-net-aot.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["./rinha-dot-net-aot"]